# Site settings
title: Yan Azdoud
description: > # this means to ignore newlines until "baseurl:"
 Yan Azdoud's homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://azdoud.github.io" # the base hostname & protocol for your site
github_username:  azdoud
markdown: kramdown
highlighter: rouge
gems: ['jekyll/scholar']

# Build settings
exclude: ['_drafts', 'convert_notebook.sh', 'nbconvert-jekyll-post.tpl', 'nbconvert_utils.py', 'nbconvert_config.py', 'readings', 'Makefile']
include: ['readings.pdf']
